import "../globals.css";
import Provider from "./provider";
import DashboardHeader from "@/src/components/header/dashboard-header";
import { Toaster } from "react-hot-toast";
import PhoneMockup from "@/src/components/phone-mockup/phone-mockup";

export const metadata = {
  title: "Devlinks App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <Provider>
      <DashboardHeader />
      <main className="box-border bg-neutral-light-grey p-4 pb-20 lg:flex lg:gap-5">
        <div className="hidden lg:flex w-5/12 items-center justify-center bg-white rounded-xl">
          <PhoneMockup />
        </div>
        <div className="flex lg:w-7/12 lg:h-[810px] flex-col gap-10 bg-white rounded-xl pt-6 pb-4 md:pt-10">
          {children}
        </div>
      </main>
      <Toaster
        position="bottom-center"
        toastOptions={{
          duration: 5000,
          style: { background: "#333333", color: "#FAFAFA" },
        }}
      />
    </Provider>
  );
}
