import { Instrument_Sans } from "next/font/google"; // using google fonts instead of provided local fonts
import "./globals.css";
import Main from "@/src/components/main/main";
import { Toaster } from "react-hot-toast";

const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Devlinks App",
  description: "Generated by create next app",
};

export default function MarketingLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`h-screen box-border overflow-auto ${instrumentSans.className}`}
      >
        <Main>
          <Toaster
            position="bottom-center"
            toastOptions={{
              duration: 5000,
              style: { background: "#333333", color: "#FAFAFA" },
            }}
          />
          {children}
        </Main>
      </body>
    </html>
  );
}
